### ISSUE TITLE
root considered invalid

### ISSUE THREAD

**Issue by ddevz** [TheXXOs/ithkapp#13]
Thanks for writing this

some roots (like roots starting with q) seem to be considered invalid by the system.

My guess is that this is caused by changes in the new version of ithkuil that was released earlier this year.

**Comment by TheXXOs** [comment]
Hi, and thanks!

In case you're not already aware, there are two current versions of Ithkuil - **New Ithkuil**/**Ithkuil IV** (the one that's now on [ithkuil.net](http://www.ithkuil.net/)), and **2011 Ithkuil**/**Ithkuil III** (the one that [used to be on ithkuil.net](http://www.ithkuil.net/00_intro.html)).

Ithkapp has been created as a translation tool for Ithkuil IV, not Ithkuil III - I've been working on it since before Ithkuil IV was officially released via the beta versions on [r/ithkuil](https://www.reddit.com/r/Ithkuil/) and the [Ithkuil discord](https://discord.gg/PMzFpYJ).
That's why some roots, like those containing **q**, are invalid - there's no q in New Ithkuil.

I _have_ been working on an Ithkuil III version of Ithkapp (although it is literally only a placeholder and I haven't worked on it for a few months now - that's why there's an Ithkuil III tag for issues), but if you want a _working_ tool for translating into Ithkuil III there's [this one by Laethiel](http://www.laethiel.fr/ithkuil/composer.php).

**Comment by ddevz** [comment]
> I _have_ been working on an Ithkuil III version

No need.  I'm interested in IV, not III.  I think the real problem is that as of yet, I have no idea what I'm actually doing when it comes to Ithkuil  :)
